apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "circleci-exporter.name" . }}
    helm.sh/chart: {{ include "circleci-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.labels -}}
    {{ .Values.labels | toYaml | nindent 4 -}}
    {{- end }}
  name: {{ include "circleci-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  CIRCLECI_TOKEN: {{ .Values.config.circleciToken | b64enc }}
type: Opaque
