name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.0.0
    - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v3.0.0
      with:
        go-version: 1.18
        check-latest: true

    - name: Tests
      run: make test

    - name: Build
      run: go build .

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v2.4.0
      - uses: actions/setup-go@d0a58c1c4d2b25278816e339b944508c875f3613 # v2.2.0
        with:
          go-version: 1.18
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376 # v3
        timeout-minutes: 5
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2
