name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15.2'

    - name: Check Style
      run: make lint

    - name: Tests
      run: make test

    - name: Build
      run: go build .
