name: Lint Charts

on:
  pull_request:
    paths:
      - "chart/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: sigstore/cosign-installer@7cc35d7fdbe70d4278a0c96779081e6fac665f88 # pin@v2.2.0

      - name: Set up Helm
        uses: azure/setup-helm@b5b231a831f96336bbfeccc1329990f0005c5bb1 # pin@v1.1
        with:
          version: v3.8.2

      - uses: actions/setup-python@v4 # pin@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@afea100a513515fbd68b0e72a7bb0ae34cb62aec # pin@v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create KIND Cluster
        uses: helm/kind-action@9e8295d178de23cbfbd8fa16cf844eec1d773a07 # pin@v1.2.0

      - name: Install Ingress Controller
        run: "helm install ingress-nginx/ingress-nginx --generate-name --set controller.service.type='NodePort' --set controller.admissionWebhooks.enabled=false"

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
